# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changesp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Changesp(object):
    def setupUi(self, Changesp):
        Changesp.setObjectName("Changesp")
        Changesp.resize(654, 161)
        self.axWidget = QAxContainer.QAxWidget(Changesp)
        self.axWidget.setProperty("geometry", QtCore.QRect(0, 0, 71, 70))
        self.axWidget.setObjectName("axWidget")
        self.axWidget_2 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_2.setProperty("geometry", QtCore.QRect(70, 0, 71, 70))
        self.axWidget_2.setObjectName("axWidget_2")
        self.axWidget_3 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_3.setProperty("geometry", QtCore.QRect(140, 0, 71, 70))
        self.axWidget_3.setObjectName("axWidget_3")
        self.axWidget_4 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_4.setProperty("geometry", QtCore.QRect(210, 0, 71, 70))
        self.axWidget_4.setObjectName("axWidget_4")
        self.axWidget_5 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_5.setProperty("geometry", QtCore.QRect(280, 0, 71, 70))
        self.axWidget_5.setObjectName("axWidget_5")
        self.axWidget_6 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_6.setProperty("geometry", QtCore.QRect(350, 0, 71, 70))
        self.axWidget_6.setObjectName("axWidget_6")
        self.axWidget_7 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_7.setProperty("geometry", QtCore.QRect(0, 70, 71, 70))
        self.axWidget_7.setObjectName("axWidget_7")
        self.axWidget_8 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_8.setProperty("geometry", QtCore.QRect(70, 70, 71, 70))
        self.axWidget_8.setObjectName("axWidget_8")
        self.axWidget_9 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_9.setProperty("geometry", QtCore.QRect(140, 70, 71, 70))
        self.axWidget_9.setObjectName("axWidget_9")
        self.axWidget_10 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_10.setProperty("geometry", QtCore.QRect(210, 70, 71, 70))
        self.axWidget_10.setObjectName("axWidget_10")
        self.axWidget_11 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_11.setProperty("geometry", QtCore.QRect(280, 70, 71, 70))
        self.axWidget_11.setObjectName("axWidget_11")
        self.axWidget_12 = QAxContainer.QAxWidget(Changesp)
        self.axWidget_12.setProperty("geometry", QtCore.QRect(350, 70, 71, 70))
        self.axWidget_12.setObjectName("axWidget_12")
        self.textEdit = QtWidgets.QTextEdit(Changesp)
        self.textEdit.setGeometry(QtCore.QRect(70, 140, 351, 21))
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Changesp)
        self.label.setGeometry(QtCore.QRect(0, 140, 81, 21))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Changesp)
        self.pushButton.setGeometry(QtCore.QRect(540, 60, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Changesp)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 110, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.treeView = QtWidgets.QTreeView(Changesp)
        self.treeView.setGeometry(QtCore.QRect(440, 0, 91, 161))
        self.treeView.setObjectName("treeView")
        self.pushButton_3 = QtWidgets.QPushButton(Changesp)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 10, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Changesp)
        QtCore.QMetaObject.connectSlotsByName(Changesp)

    def retranslateUi(self, Changesp):
        _translate = QtCore.QCoreApplication.translate
        Changesp.setWindowTitle(_translate("Changesp", "一键换背包"))
        self.label.setText(_translate("Changesp", "输入精灵序号"))
        self.pushButton.setText(_translate("Changesp", "保存背包"))
        self.pushButton_2.setText(_translate("Changesp", "一键换背包"))
        self.pushButton_3.setText(_translate("Changesp", "预览背包"))
from PyQt5 import QAxContainer
