# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nono.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Nono(object):
    def setupUi(self, Nono):
        Nono.setObjectName("Nono")
        Nono.resize(558, 665)
        self.label = QtWidgets.QLabel(Nono)
        self.label.setGeometry(QtCore.QRect(120, 340, 254, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/nono3.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Nono)
        self.label_2.setGeometry(QtCore.QRect(330, 420, 46, 46))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/buff_VIP_5.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Nono)
        self.label_3.setGeometry(QtCore.QRect(340, 470, 41, 16))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Nono)
        self.label_4.setGeometry(QtCore.QRect(50, 0, 396, 345))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Nono)
        self.label_5.setGeometry(QtCore.QRect(240, 270, 311, 99))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/nonotip.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Nono)
        self.label_6.setGeometry(QtCore.QRect(260, 280, 271, 81))
        self.label_6.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"造字工房力黑（非商用）常规体\";\n"
"")
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(True)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Nono)
        self.label_7.setGeometry(QtCore.QRect(70, 490, 50, 50))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/nonobiao.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Nono)
        self.label_8.setGeometry(QtCore.QRect(120, 550, 61, 61))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/nonobiao.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Nono)
        self.label_9.setGeometry(QtCore.QRect(120, 420, 50, 50))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/nonobiao.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Nono)
        self.label_10.setGeometry(QtCore.QRect(130, 440, 41, 21))
        self.label_10.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"造字工房力黑（非商用）常规体\";\n"
"")
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setLineWidth(1)
        self.label_10.setScaledContents(False)
        self.label_10.setWordWrap(True)
        self.label_10.setOpenExternalLinks(False)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Nono)
        self.label_11.setGeometry(QtCore.QRect(80, 510, 41, 21))
        self.label_11.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"造字工房力黑（非商用）常规体\";\n"
"")
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setLineWidth(1)
        self.label_11.setScaledContents(False)
        self.label_11.setWordWrap(True)
        self.label_11.setOpenExternalLinks(False)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Nono)
        self.label_12.setGeometry(QtCore.QRect(130, 560, 41, 41))
        self.label_12.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"造字工房力黑（非商用）常规体\";\n"
"")
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setLineWidth(1)
        self.label_12.setScaledContents(False)
        self.label_12.setWordWrap(True)
        self.label_12.setOpenExternalLinks(False)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Nono)
        self.label_13.setGeometry(QtCore.QRect(290, 550, 61, 61))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/nonobiao.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Nono)
        self.label_14.setGeometry(QtCore.QRect(300, 560, 41, 41))
        self.label_14.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"造字工房力黑（非商用）常规体\";\n"
"")
        self.label_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_14.setLineWidth(1)
        self.label_14.setScaledContents(False)
        self.label_14.setWordWrap(True)
        self.label_14.setOpenExternalLinks(False)
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Nono)
        QtCore.QMetaObject.connectSlotsByName(Nono)

    def retranslateUi(self, Nono):
        _translate = QtCore.QCoreApplication.translate
        Nono.setWindowTitle(_translate("Nono", "Form"))
        self.label_3.setText(_translate("Nono", "30:00"))
        self.label_4.setText(_translate("Nono", "TextLabel"))
        self.label_6.setText(_translate("Nono", "精灵阵容已截图完毕"))
        self.label_10.setText(_translate("Nono", "刷新"))
        self.label_11.setText(_translate("Nono", "识别"))
        self.label_12.setText(_translate("Nono", "自动确认"))
        self.label_14.setText(_translate("Nono", "自动补p"))
import resource_rc
